target:	pa4

pa4:	main.cpp Robot.h bulldozer.h roomba.h humanic.h optimusprime.h robocop.h
	g++ -std=c++11 main.cpp Robot.cpp bulldozer.cpp roomba.cpp optimusprime.cpp robocop.cpp -o pa4

clean:
		rm pa4
